version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest_api
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - bruno-network
  rest-api:
    image: brunoliragarcia/rest-api
    restart: always
    build: C:\Users\User\Documents\api\rest-with-spring-boot-and-java
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rest_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - bruno-network
networks:
  bruno-network:
    driver: bridge
